export interface DisabledRule {
  settingKey: string;
  operator: 'eq' | 'neq';
  value: string;
  reason: string;
}

export interface SettingDefinition {
  key: string;
  envVar: string;
  legacyEnvVar?: string;
  label: string;
  description: string;
  category: string;
  type: 'string' | 'number' | 'boolean' | 'select';
  default: string | number | boolean;
  options?: string[];
  sensitive?: boolean;
  requiresRestart?: boolean;
  envOnly?: boolean;
  validate?: (v: string) => boolean;
  disabledWhen?: DisabledRule[];
  uiHint?: 'tags';
  maxTags?: number;
  min?: number;
  max?: number;
}

export const SETTINGS_REGISTRY: SettingDefinition[] = [
  // --- API Keys ---
  {
    key: 'TMDB_API_KEY',
    envVar: 'TMDB_API_KEY',
    legacyEnvVar: 'TMDB_API',
    label: 'TMDB API Key',
    description: 'The Movie Database API key for metadata lookups',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'TVDB_API_KEY',
    envVar: 'TVDB_API_KEY',
    label: 'TVDB API Key',
    description: 'TheTVDB API key for TV metadata',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'FANART_API_KEY',
    envVar: 'FANART_API_KEY',
    label: 'Fanart.tv API Key',
    description: 'Fanart.tv API key for artwork',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'RPDB_API_KEY',
    envVar: 'RPDB_API_KEY',
    label: 'RPDB API Key',
    description: 'Rating Poster Database API key',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'MDBLIST_API_KEY',
    envVar: 'MDBLIST_API_KEY',
    label: 'MDBList API Key',
    description: 'MDBList API key for lists and ratings',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'GEMINI_API_KEY',
    envVar: 'GEMINI_API_KEY',
    label: 'Gemini API Key',
    description: 'Google Gemini API key for AI features',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'BUILT_IN_TMDB_API_KEY',
    envVar: 'BUILT_IN_TMDB_API_KEY',
    label: 'Built-in TMDB Key',
    description: 'Server-side TMDB key used as fallback when users have no personal key',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'BUILT_IN_TVDB_API_KEY',
    envVar: 'BUILT_IN_TVDB_API_KEY',
    label: 'Built-in TVDB Key',
    description: 'Server-side TVDB key used as fallback when users have no personal key',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'BUILT_IN_FANART_API_KEY',
    envVar: 'BUILT_IN_FANART_API_KEY',
    label: 'Built-in Fanart Key',
    description: 'Server-side Fanart.tv key used as fallback',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'BUILT_IN_RPDB_API_KEY',
    envVar: 'BUILT_IN_RPDB_API_KEY',
    label: 'Built-in RPDB Key',
    description: 'Server-side RPDB key used as fallback',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },

  // --- OAuth (env-only) ---
  {
    key: 'TRAKT_CLIENT_ID',
    envVar: 'TRAKT_CLIENT_ID',
    label: 'Trakt Client ID',
    description: 'Trakt OAuth application client ID. Changing invalidates all user tokens.',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'TRAKT_CLIENT_SECRET',
    envVar: 'TRAKT_CLIENT_SECRET',
    label: 'Trakt Client Secret',
    description: 'Trakt OAuth application client secret',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'TRAKT_REDIRECT_URI',
    envVar: 'TRAKT_REDIRECT_URI',
    label: 'Trakt Redirect URI',
    description: 'Trakt OAuth redirect URI override',
    category: 'OAuth',
    type: 'string',
    default: '',
    envOnly: true,
  },
  {
    key: 'SIMKL_CLIENT_ID',
    envVar: 'SIMKL_CLIENT_ID',
    label: 'Simkl Client ID',
    description: 'Simkl OAuth application client ID. Changing invalidates all user tokens.',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'SIMKL_CLIENT_SECRET',
    envVar: 'SIMKL_CLIENT_SECRET',
    label: 'Simkl Client Secret',
    description: 'Simkl OAuth application client secret',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'SIMKL_REDIRECT_URI',
    envVar: 'SIMKL_REDIRECT_URI',
    label: 'Simkl Redirect URI',
    description: 'Simkl OAuth redirect URI override',
    category: 'OAuth',
    type: 'string',
    default: '',
    envOnly: true,
  },
  {
    key: 'ANILIST_CLIENT_ID',
    envVar: 'ANILIST_CLIENT_ID',
    label: 'AniList Client ID',
    description: 'AniList OAuth application client ID. Changing invalidates all user tokens.',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'ANILIST_CLIENT_SECRET',
    envVar: 'ANILIST_CLIENT_SECRET',
    label: 'AniList Client Secret',
    description: 'AniList OAuth application client secret',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'ANILIST_REDIRECT_URI',
    envVar: 'ANILIST_REDIRECT_URI',
    label: 'AniList Redirect URI',
    description: 'AniList OAuth redirect URI override',
    category: 'OAuth',
    type: 'string',
    default: '',
    envOnly: true,
  },

  // --- Cache ---
  {
    key: 'META_TTL',
    envVar: 'META_TTL',
    label: 'Meta Cache TTL',
    description: 'Time-to-live for metadata cache entries in seconds',
    category: 'Cache',
    type: 'number',
    default: 604800,
  },
  {
    key: 'CATALOG_TTL',
    envVar: 'CATALOG_TTL',
    label: 'Catalog Cache TTL',
    description: 'Time-to-live for catalog cache entries in seconds',
    category: 'Cache',
    type: 'number',
    default: 86400,
  },
  {
    key: 'ANILIST_CATALOG_TTL',
    envVar: 'ANILIST_CATALOG_TTL',
    label: 'AniList Catalog TTL',
    description: 'Time-to-live for AniList catalog entries in seconds',
    category: 'Cache',
    type: 'number',
    default: 86400,
  },
  {
    key: 'TMDB_TRENDING_TTL',
    envVar: 'TMDB_TRENDING_TTL',
    label: 'TMDB Trending TTL',
    description: 'Time-to-live for TMDB trending cache in seconds',
    category: 'Cache',
    type: 'number',
    default: 10800,
  },
  {
    key: 'CONFIG_CACHE_TTL_SEC',
    envVar: 'CONFIG_CACHE_TTL_SEC',
    label: 'Config Cache TTL',
    description: 'Time-to-live for user config cache in seconds',
    category: 'Cache',
    type: 'number',
    default: 300,
  },
  {
    key: 'CACHE_COMPRESSION_ENABLED',
    envVar: 'CACHE_COMPRESSION_ENABLED',
    label: 'Cache Compression',
    description: 'Enable gzip compression for cached data',
    category: 'Cache',
    type: 'boolean',
    default: false,
  },
  {
    key: 'CACHE_COMPRESSION_MIN_BYTES',
    envVar: 'CACHE_COMPRESSION_MIN_BYTES',
    label: 'Compression Min Bytes',
    description: 'Minimum payload size in bytes before compression is applied',
    category: 'Cache',
    type: 'number',
    default: 1024,
  },
  {
    key: 'CACHE_MAX_RETRIES',
    envVar: 'CACHE_MAX_RETRIES',
    label: 'Cache Max Retries',
    description: 'Max retries for cache read/write operations',
    category: 'Cache',
    type: 'number',
    default: 3,
  },

  // --- Features ---
  {
    key: 'DISABLE_TRAKT_SEARCH',
    envVar: 'DISABLE_TRAKT_SEARCH',
    label: 'Disable Trakt Search',
    description: 'Disable Trakt as a search provider',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'DISABLE_METRICS',
    envVar: 'DISABLE_METRICS',
    label: 'Disable Metrics',
    description: 'Disable request tracking and analytics',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'DISABLE_GUEST_MODE',
    envVar: 'DISABLE_GUEST_MODE',
    label: 'Disable Guest Mode',
    description: 'Disable guest access to the dashboard',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'CUSTOM_DESCRIPTION_BLURB',
    envVar: 'CUSTOM_DESCRIPTION_BLURB',
    label: 'Custom Description Blurb',
    description: 'Custom text appended to the addon description',
    category: 'Features',
    type: 'string',
    default: '',
  },
  {
    key: 'ADDON_NAME_SUFFIX',
    envVar: 'ADDON_NAME_SUFFIX',
    label: 'Addon Name Suffix',
    description: 'Custom suffix appended to the addon name in Stremio',
    category: 'Features',
    type: 'string',
    default: '',
  },
  {
    key: 'ADDON_LOGO_URL',
    envVar: 'ADDON_LOGO_URL',
    label: 'Addon Logo URL',
    description: 'Custom logo URL for the addon in Stremio',
    category: 'Features',
    type: 'string',
    default: '',
  },
  {
    key: 'POSTER_PROXY_PREFIX_URL',
    envVar: 'POSTER_PROXY_PREFIX_URL',
    label: 'Poster Proxy URL',
    description: 'Prefix URL for proxying poster images',
    category: 'Features',
    type: 'string',
    default: '',
  },
  {
    key: 'MAX_CATALOGS',
    envVar: 'MAX_CATALOGS',
    label: 'Max Catalogs',
    description: 'Maximum number of catalogs a user can configure (empty = no limit)',
    category: 'Features',
    type: 'number',
    default: '',
  },
  {
    key: 'CATALOG_LIST_ITEMS_SIZE',
    envVar: 'CATALOG_LIST_ITEMS_SIZE',
    label: 'Catalog List Page Size',
    description: 'Number of items per catalog page',
    category: 'Features',
    type: 'number',
    default: 20,
  },
  {
    key: 'ENABLE_SELF_HEALING',
    envVar: 'ENABLE_SELF_HEALING',
    label: 'Self-Healing Cache',
    description: 'Automatically repair corrupted cache entries',
    category: 'Features',
    type: 'boolean',
    default: false,
    requiresRestart: true,
  },

  // --- Essential Warming ---
  {
    key: 'ENABLE_CACHE_WARMING',
    envVar: 'ENABLE_CACHE_WARMING',
    label: 'Enable Cache Warming',
    description: 'Enable automatic background essential cache warming',
    category: 'Essential Warming',
    type: 'boolean',
    default: true,
    requiresRestart: true,
  },
  {
    key: 'CACHE_WARMING_INTERVAL',
    envVar: 'CACHE_WARMING_INTERVAL',
    label: 'Warming Interval (min)',
    description: 'Minutes between essential cache warming runs',
    category: 'Essential Warming',
    type: 'number',
    default: 720,
    requiresRestart: true,
  },
  {
    key: 'CACHE_WARM_INTERVAL_HOURS',
    envVar: 'CACHE_WARM_INTERVAL_HOURS',
    label: 'Popular Warming Interval (hrs)',
    description: 'Hours between popular content warming runs',
    category: 'Essential Warming',
    type: 'number',
    default: 24,
    min: 12,
    validate: (v: string) => parseInt(v, 10) >= 12,
    requiresRestart: true,
  },
  {
    key: 'CACHE_WARM_LANGUAGE',
    envVar: 'CACHE_WARM_LANGUAGE',
    label: 'Warming Language',
    description: 'Language code for cache warming content (e.g. en-US)',
    category: 'Essential Warming',
    type: 'string',
    default: 'en-US',
  },
  {
    key: 'TMDB_POPULAR_WARMING_ENABLED',
    envVar: 'TMDB_POPULAR_WARMING_ENABLED',
    label: 'TMDB Popular Warming',
    description: 'Enable TMDB popular content warming',
    category: 'Essential Warming',
    type: 'boolean',
    default: true,
  },

  // --- Comprehensive Warming ---
  {
    key: 'CACHE_WARMUP_MODE',
    envVar: 'CACHE_WARMUP_MODE',
    label: 'Warmup Mode',
    description: 'Cache warmup mode: essential (default) or comprehensive',
    category: 'Comprehensive Warming',
    type: 'select',
    default: 'essential',
    options: ['essential', 'comprehensive'],
  },
  {
    key: 'CACHE_WARMUP_UUIDS',
    envVar: 'CACHE_WARMUP_UUIDS',
    label: 'Warmup UUIDs',
    description: 'Comma-separated UUIDs to warm catalogs for in comprehensive mode (max 5)',
    category: 'Comprehensive Warming',
    type: 'string',
    default: '',
    uiHint: 'tags',
    maxTags: 5,
    validate: (v: string) => v.split(',').filter(s => s.trim()).length <= 5,
  },
  {
    key: 'CATALOG_WARMUP_INTERVAL_HOURS',
    envVar: 'CATALOG_WARMUP_INTERVAL_HOURS',
    label: 'Warmup Interval (hrs)',
    description: 'Hours between comprehensive warming runs (supports fractional like 0.5)',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 24,
    min: 12,
    validate: (v: string) => parseFloat(v) >= 12,
  },
  {
    key: 'CATALOG_WARMUP_INITIAL_DELAY_SECONDS',
    envVar: 'CATALOG_WARMUP_INITIAL_DELAY_SECONDS',
    label: 'Initial Delay (sec)',
    description: 'Seconds to wait after startup before first comprehensive warming run',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 300,
  },
  {
    key: 'CATALOG_WARMUP_MAX_PAGES_PER_CATALOG',
    envVar: 'CATALOG_WARMUP_MAX_PAGES_PER_CATALOG',
    label: 'Max Pages Per Catalog',
    description: 'Maximum pages to warm per catalog',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 100,
  },
  {
    key: 'CATALOG_WARMUP_TASK_DELAY_MS',
    envVar: 'CATALOG_WARMUP_TASK_DELAY_MS',
    label: 'Task Delay (ms)',
    description: 'Delay between individual warming tasks to avoid rate limiting',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 100,
  },
  {
    key: 'CATALOG_WARMUP_RESUME_ON_RESTART',
    envVar: 'CATALOG_WARMUP_RESUME_ON_RESTART',
    label: 'Resume on Restart',
    description: 'Resume warming progress after container restart',
    category: 'Comprehensive Warming',
    type: 'boolean',
    default: true,
  },
  {
    key: 'CATALOG_WARMUP_QUIET_HOURS_ENABLED',
    envVar: 'CATALOG_WARMUP_QUIET_HOURS_ENABLED',
    label: 'Quiet Hours Enabled',
    description: 'Pause warming during quiet hours',
    category: 'Comprehensive Warming',
    type: 'boolean',
    default: false,
  },
  {
    key: 'CATALOG_WARMUP_QUIET_HOURS',
    envVar: 'CATALOG_WARMUP_QUIET_HOURS',
    label: 'Quiet Hours Range',
    description: 'Time range for quiet hours (e.g. 02:00-06:00)',
    category: 'Comprehensive Warming',
    type: 'string',
    default: '02:00-06:00',
  },
  {
    key: 'CATALOG_WARMUP_LOG_LEVEL',
    envVar: 'CATALOG_WARMUP_LOG_LEVEL',
    label: 'Log Level',
    description: 'Log verbosity for comprehensive warming',
    category: 'Comprehensive Warming',
    type: 'select',
    default: 'info',
    options: ['debug', 'info', 'warn', 'error'],
  },
  {
    key: 'CATALOG_WARMUP_AUTO_ON_VERSION_CHANGE',
    envVar: 'CATALOG_WARMUP_AUTO_ON_VERSION_CHANGE',
    label: 'Auto on Version Change',
    description: 'Trigger comprehensive warming after addon version update',
    category: 'Comprehensive Warming',
    type: 'boolean',
    default: false,
  },
  {
    key: 'POSTER_WARMUP_URL',
    envVar: 'POSTER_WARMUP_URL',
    label: 'Poster Warmup URL',
    description: 'Base URL for poster warming requests',
    category: 'Comprehensive Warming',
    type: 'string',
    default: '',
  },
  {
    key: 'POSTER_WARMUP_DELAY_MS',
    envVar: 'POSTER_WARMUP_DELAY_MS',
    label: 'Poster Warmup Delay (ms)',
    description: 'Delay between poster warmup requests',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 50,
  },
  {
    key: 'POSTER_WARMUP_CONCURRENCY',
    envVar: 'POSTER_WARMUP_CONCURRENCY',
    label: 'Poster Warmup Concurrency',
    description: 'Number of concurrent poster warmup requests',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 1,
    min: 1,
    validate: (v: string) => parseInt(v, 10) >= 1,
  },

  // --- MAL Warming ---
  {
    key: 'MAL_WARMUP_ENABLED',
    envVar: 'MAL_WARMUP_ENABLED',
    label: 'MAL Warmup Enabled',
    description: 'Enable MyAnimeList catalog warming',
    category: 'MAL Warming',
    type: 'boolean',
    default: false,
  },
  {
    key: 'MAL_WARMUP_INTERVAL_HOURS',
    envVar: 'MAL_WARMUP_INTERVAL_HOURS',
    label: 'MAL Warmup Interval (hrs)',
    description: 'Hours between MAL warming runs',
    category: 'MAL Warming',
    type: 'number',
    default: 24,
  },
  {
    key: 'MAL_WARMUP_INITIAL_DELAY_SECONDS',
    envVar: 'MAL_WARMUP_INITIAL_DELAY_SECONDS',
    label: 'MAL Initial Delay (sec)',
    description: 'Seconds to wait after startup before MAL warming',
    category: 'MAL Warming',
    type: 'number',
    default: 300,
  },
  {
    key: 'MAL_WARMUP_TASK_DELAY_MS',
    envVar: 'MAL_WARMUP_TASK_DELAY_MS',
    label: 'MAL Task Delay (ms)',
    description: 'Delay between MAL warming requests',
    category: 'MAL Warming',
    type: 'number',
    default: 100,
  },
  {
    key: 'MAL_WARMUP_DECADES',
    envVar: 'MAL_WARMUP_DECADES',
    label: 'MAL Warmup Decades',
    description: 'Comma-separated decades to warm (e.g. 2020s,2010s)',
    category: 'MAL Warming',
    type: 'string',
    default: '',
    uiHint: 'tags',
  },
  {
    key: 'MAL_WARMUP_PRIORITY_PAGES',
    envVar: 'MAL_WARMUP_PRIORITY_PAGES',
    label: 'MAL Priority Pages',
    description: 'Number of pages to fetch for priority genres',
    category: 'MAL Warming',
    type: 'number',
    default: 3,
  },
  {
    key: 'MAL_WARMUP_LOG_LEVEL',
    envVar: 'MAL_WARMUP_LOG_LEVEL',
    label: 'MAL Log Level',
    description: 'Log verbosity for MAL warming',
    category: 'MAL Warming',
    type: 'select',
    default: 'info',
    options: ['debug', 'info', 'warn', 'error'],
  },
  {
    key: 'MAL_WARMUP_QUIET_HOURS_ENABLED',
    envVar: 'MAL_WARMUP_QUIET_HOURS_ENABLED',
    label: 'MAL Quiet Hours',
    description: 'Pause MAL warming during quiet hours',
    category: 'MAL Warming',
    type: 'boolean',
    default: false,
  },
  {
    key: 'MAL_WARMUP_QUIET_HOURS_RANGE',
    envVar: 'MAL_WARMUP_QUIET_HOURS_RANGE',
    label: 'MAL Quiet Hours Range',
    description: 'Time range for MAL quiet hours',
    category: 'MAL Warming',
    type: 'string',
    default: '02:00-06:00',
  },

  // --- Rate Limiting ---
  {
    key: 'POSTER_PROXY_TIMEOUT_MS',
    envVar: 'POSTER_PROXY_TIMEOUT_MS',
    label: 'Poster Proxy Timeout (ms)',
    description: 'Milliseconds to wait for an upstream poster/art image before serving the fallback. Raise this if a slow rating/poster-generation service times out on first render.',
    category: 'Rate Limiting',
    type: 'number',
    default: 10000,
  },
  {
    key: 'JIKAN_MAX_CONCURRENT',
    envVar: 'JIKAN_MAX_CONCURRENT',
    label: 'Jikan Max Concurrent',
    description: 'Maximum concurrent requests to Jikan API',
    category: 'Rate Limiting',
    type: 'number',
    default: 3,
    requiresRestart: true,
  },
  {
    key: 'JIKAN_MAX_PER_MINUTE',
    envVar: 'JIKAN_MAX_PER_MINUTE',
    label: 'Jikan Max Per Minute',
    description: 'Maximum requests per minute to Jikan API',
    category: 'Rate Limiting',
    type: 'number',
    default: 60,
    requiresRestart: true,
  },
  {
    key: 'JIKAN_MIN_INTERVAL',
    envVar: 'JIKAN_MIN_INTERVAL',
    label: 'Jikan Min Interval (ms)',
    description: 'Minimum milliseconds between Jikan requests',
    category: 'Rate Limiting',
    type: 'number',
    default: 334,
    requiresRestart: true,
  },
  {
    key: 'JIKAN_API_BASE',
    envVar: 'JIKAN_API_BASE',
    label: 'Jikan API Base URL',
    description: 'Base URL for Jikan API (self-hosted or default)',
    category: 'Rate Limiting',
    type: 'string',
    default: 'https://api.jikan.moe/v4',
    requiresRestart: true,
  },
  {
    key: 'TEST_KEYS_RATE_LIMIT_PER_MIN',
    envVar: 'TEST_KEYS_RATE_LIMIT_PER_MIN',
    label: 'Key Test Rate Limit',
    description: 'Max API key test requests per minute',
    category: 'Rate Limiting',
    type: 'number',
    default: 60,
  },
  {
    key: 'SIMKL_TRENDING_PAGE_SIZE_OPTIONS',
    envVar: 'SIMKL_TRENDING_PAGE_SIZE_OPTIONS',
    label: 'Simkl Trending Page Sizes',
    description: 'Comma-separated page size options for Simkl trending',
    category: 'Rate Limiting',
    type: 'string',
    default: '50,100',
    uiHint: 'tags',
  },

  // --- Data Updates ---
  {
    key: 'IMDB_RATINGS_UPDATE_INTERVAL_HOURS',
    envVar: 'IMDB_RATINGS_UPDATE_INTERVAL_HOURS',
    label: 'IMDb Ratings Update (hrs)',
    description: 'Hours between IMDb ratings dataset updates',
    category: 'Data Updates',
    type: 'number',
    default: 24,
    requiresRestart: true,
  },
  {
    key: 'ANIME_LIST_UPDATE_INTERVAL_HOURS',
    envVar: 'ANIME_LIST_UPDATE_INTERVAL_HOURS',
    label: 'Anime List Update (hrs)',
    description: 'Hours between anime list mapping updates',
    category: 'Data Updates',
    type: 'number',
    default: 168,
    requiresRestart: true,
  },
  {
    key: 'WIKI_MAPPER_UPDATE_INTERVAL_HOURS',
    envVar: 'WIKI_MAPPER_UPDATE_INTERVAL_HOURS',
    label: 'Wiki Mapper Update (hrs)',
    description: 'Hours between wiki mapper data updates',
    category: 'Data Updates',
    type: 'number',
    default: 168,
    requiresRestart: true,
  },
  {
    key: 'KITSU_TO_IMDB_UPDATE_INTERVAL_HOURS',
    envVar: 'KITSU_TO_IMDB_UPDATE_INTERVAL_HOURS',
    label: 'Kitsu-IMDb Update (hrs)',
    description: 'Hours between Kitsu to IMDb mapping updates',
    category: 'Data Updates',
    type: 'number',
    default: 168,
    requiresRestart: true,
  },
  {
    key: 'TRAKT_ANIME_MOVIES_UPDATE_INTERVAL_HOURS',
    envVar: 'TRAKT_ANIME_MOVIES_UPDATE_INTERVAL_HOURS',
    label: 'Trakt Anime Movies Update (hrs)',
    description: 'Hours between Trakt anime movies list updates',
    category: 'Data Updates',
    type: 'number',
    default: 168,
    requiresRestart: true,
  },

  // --- Proxy ---
  {
    key: 'HTTP_PROXY',
    envVar: 'HTTP_PROXY',
    label: 'HTTP Proxy',
    description: 'HTTP proxy URL for outgoing requests',
    category: 'Proxy',
    type: 'string',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'HTTPS_PROXY',
    envVar: 'HTTPS_PROXY',
    label: 'HTTPS Proxy',
    description: 'HTTPS proxy URL for outgoing requests',
    category: 'Proxy',
    type: 'string',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'TMDB_SOCKS_PROXY_URL',
    envVar: 'TMDB_SOCKS_PROXY_URL',
    label: 'TMDB SOCKS Proxy',
    description: 'SOCKS proxy URL specifically for TMDB requests',
    category: 'Proxy',
    type: 'string',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'MAL_SOCKS_PROXY_URL',
    envVar: 'MAL_SOCKS_PROXY_URL',
    label: 'MAL SOCKS Proxy',
    description: 'SOCKS proxy URL specifically for MAL/Jikan requests',
    category: 'Proxy',
    type: 'string',
    default: '',
    requiresRestart: true,
  },

  // --- Diagnostics ---
  {
    key: 'LOG_BUFFER_SIZE',
    envVar: 'LOG_BUFFER_SIZE',
    label: 'Log Buffer Size',
    description: 'Maximum number of log entries kept in memory',
    category: 'Diagnostics',
    type: 'number',
    default: 100000,
    requiresRestart: true,
  },
  {
    key: 'CACHE_HEALTH_CHECK_INTERVAL',
    envVar: 'CACHE_HEALTH_CHECK_INTERVAL',
    label: 'Cache Health Check (sec)',
    description: 'Seconds between cache health check runs',
    category: 'Diagnostics',
    type: 'number',
    default: 300,
  },
  {
    key: 'CACHE_CORRUPTED_THRESHOLD',
    envVar: 'CACHE_CORRUPTED_THRESHOLD',
    label: 'Corrupted Cache Threshold',
    description: 'Number of corrupted entries before triggering self-healing',
    category: 'Diagnostics',
    type: 'number',
    default: 10,
  },
  {
    key: 'MAX_TRACKED_KEYS',
    envVar: 'MAX_TRACKED_KEYS',
    label: 'Max Tracked Keys',
    description: 'Maximum number of cache keys to track for analytics',
    category: 'Diagnostics',
    type: 'number',
    default: 10000,
  },
  {
    key: 'DASHBOARD_METADATA_LANGUAGE',
    envVar: 'DASHBOARD_METADATA_LANGUAGE',
    label: 'Dashboard Title Language',
    description: 'Preferred language code for popular-content titles in the dashboard (e.g. en). A title captured in this language is not overwritten by requests in other languages. Leave blank to always use the most recent request.',
    category: 'Diagnostics',
    type: 'string',
    default: 'en',
  },

  // --- Server (bootstrap, env-only) ---
  {
    key: 'PORT',
    envVar: 'PORT',
    label: 'Server Port',
    description: 'HTTP port the addon listens on',
    category: 'Server',
    type: 'number',
    default: 3232,
    requiresRestart: true,
    envOnly: true,
  },
  {
    key: 'HOST_NAME',
    envVar: 'HOST_NAME',
    label: 'Host Name',
    description: 'Public URL of this addon instance',
    category: 'Server',
    type: 'string',
    default: '',
    requiresRestart: true,
    envOnly: true,
  },
  {
    key: 'DATABASE_URI',
    envVar: 'DATABASE_URI',
    label: 'Database URI',
    description: 'SQLite or PostgreSQL connection string',
    category: 'Server',
    type: 'string',
    default: '',
    sensitive: true,
    requiresRestart: true,
    envOnly: true,
  },
  {
    key: 'REDIS_URL',
    envVar: 'REDIS_URL',
    label: 'Redis URL',
    description: 'Redis connection URL for caching',
    category: 'Server',
    type: 'string',
    default: '',
    sensitive: true,
    requiresRestart: true,
    envOnly: true,
  },
  {
    key: 'ADMIN_KEY',
    envVar: 'ADMIN_KEY',
    label: 'Admin Key',
    description: 'Admin authentication key for the dashboard',
    category: 'Server',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'ADDON_PASSWORD',
    envVar: 'ADDON_PASSWORD',
    label: 'Addon Password',
    description: 'Password required to access the addon configure page',
    category: 'Server',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
];

// Rules: when a setting has a certain value, other settings become disabled.
// Evaluated server-side so the frontend gets a flat disabled/disabledReason per setting.
export interface ConditionalRule {
  when: { key: string; eq: string };
  disable: { keys?: string[]; categories?: string[] };
  reason: string;
}

export const CONDITIONAL_RULES: ConditionalRule[] = [
  {
    when: { key: 'CACHE_WARMUP_MODE', eq: 'comprehensive' },
    disable: { categories: ['MAL Warming'], keys: ['TMDB_POPULAR_WARMING_ENABLED'] },
    reason: 'Disabled in comprehensive mode',
  },
  {
    when: { key: 'CACHE_WARMUP_MODE', eq: 'essential' },
    disable: {
      keys: [
        'CACHE_WARMUP_UUIDS', 'CATALOG_WARMUP_INTERVAL_HOURS', 'CATALOG_WARMUP_INITIAL_DELAY_SECONDS',
        'CATALOG_WARMUP_MAX_PAGES_PER_CATALOG', 'CATALOG_WARMUP_TASK_DELAY_MS',
        'CATALOG_WARMUP_RESUME_ON_RESTART', 'CATALOG_WARMUP_QUIET_HOURS_ENABLED',
        'CATALOG_WARMUP_QUIET_HOURS', 'CATALOG_WARMUP_LOG_LEVEL',
        'CATALOG_WARMUP_AUTO_ON_VERSION_CHANGE', 'POSTER_WARMUP_URL',
        'POSTER_WARMUP_DELAY_MS', 'POSTER_WARMUP_CONCURRENCY',
      ],
    },
    reason: 'Warmup mode is set to essential',
  },
  {
    when: { key: 'ENABLE_CACHE_WARMING', eq: 'false' },
    disable: {
      keys: [
        'CACHE_WARMING_INTERVAL', 'CACHE_WARM_INTERVAL_HOURS',
        'CACHE_WARM_LANGUAGE', 'TMDB_POPULAR_WARMING_ENABLED',
      ],
    },
    reason: 'Essential cache warming is disabled',
  },
];

const registryMap = new Map<string, SettingDefinition>();
for (const def of SETTINGS_REGISTRY) {
  registryMap.set(def.key, def);
}

export function getSettingDefinition(key: string): SettingDefinition | undefined {
  return registryMap.get(key);
}

export function getSettingsByCategory(): Map<string, SettingDefinition[]> {
  const categories = new Map<string, SettingDefinition[]>();
  for (const def of SETTINGS_REGISTRY) {
    const list = categories.get(def.category) || [];
    list.push(def);
    categories.set(def.category, list);
  }
  return categories;
}
